steps:
  - label: "AMDGPU Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10" # oldest
          - "1"    # latest
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      rocm: "*"
    env:
      GROUP: "AMDGPU_Ext"
    timeout_in_minutes: 60
