steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10" # oldest
          #- "1"    # latest
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    agents:
      queue: "juliaecosystem"
      cuda: "*"
    env:
      GROUP: "CUDA_Ext"
    timeout_in_minutes: 60
    if: | 
        // Don't run Buildkite if the commit message includes the text [skip ci], [ci skip], or [no ci]
        // Don't run Buildkite for PR draft
        // Only run Buildkite when new commits and PR are made to main branch
        build.message !~ /\[skip ci\]/ &&
        build.message !~ /\[ci skip\]/ &&
        build.message !~ /\[no ci\]/   &&
        !build.pull_request.draft      &&
        (build.branch =~ /main/ || build.pull_request.base_branch =~ /main/)
