# see: https://github.com/staticfloat/forerunner-buildkite-plugin
steps:
  - label: ":runner: Dynamically launch pipelines"
    plugins:
      - staticfloat/forerunner:
          watch:
            - ".buildkite/pipeline.yml"
            - ".buildkite/GPU_Ext.yml"
            - "src/**"
            - "ext/QuantumToolboxCUDAExt.jl"
            - "ext/QuantumToolboxMetalExt.jl"
            - "test/runtests.jl"
            - "test/ext-test/cuda_ext.jl"
            - "test/ext-test/metal_ext.jl"
            - "Project.toml"
          target: ".buildkite/GPU_Ext.yml"
    agents:
      queue: "juliagpu"
