# see: https://github.com/staticfloat/forerunner-buildkite-plugin
steps:
  - label: ":runner: Dynamically launch pipelines"
    plugins:
      - staticfloat/forerunner: # CUDA.jl tests
          watch:
            - ".buildkite/pipeline.yml"
            - ".buildkite/CUDA_Ext.yml"
            - "src/**"
            - "ext/QuantumToolboxCUDAExt.jl"
            - "test/runtests.jl"
            - "test/ext-test/gpu/**"
            - "Project.toml"
          target: ".buildkite/CUDA_Ext.yml"
      - staticfloat/forerunner: # Metal.jl tests
          watch:
            - ".buildkite/pipeline.yml"
            - ".buildkite/Metal_Ext.yml"
            - "src/**"
            - "ext/QuantumToolboxMetalExt.jl"
            - "test/runtests.jl"
            - "test/ext-test/metal_ext.jl"
            - "Project.toml"
          target: ".buildkite/Metal_Ext.yml"
    agents:
      queue: "juliagpu"
